"""empty message

Revision ID: 16765413264e
Revises: 8b949eee584b
Create Date: 2023-06-22 23:25:01.013417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16765413264e'
down_revision = '8b949eee584b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'conta', ['conta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conta_id')

    # ### end Alembic commands ###
